---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops_exam
  name: question6
spec:
  ports: ~
  replicas: 3
  selector:
    matchLabels:
      app: devops_exam
  template:
    metadata:
      labels:
        app: devops_exam
    spec:
      containers:
        -
          image: afokepeniel/devops-project:v3
          name: webpage3

